import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["DM Sans", "system-ui", "sans-serif"],
        display: ["Cormorant Garamond", "Georgia", "serif"],
        serif: ["Cormorant Garamond", "Georgia", "serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        surface: "hsl(var(--surface))",
        "surface-2": "hsl(var(--surface-2))",
        brand: {
          50: "#f0fdfa",
          100: "#ccfbf1",
          200: "#99f6e4",
          300: "#5eead4",
          400: "#2dd4bf",
          500: "#14b8a6",
          600: "#0d9488",
          700: "#0f766e",
          800: "#115e59",
          900: "#134e4a",
        },
        gold: {
          50: "#fffdf0",
          100: "#fff8d4",
          200: "#ffeea8",
          300: "#ffe06e",
          400: "#f5cc3a",
          500: "#D4AF37",
          600: "#b8930a",
          700: "#96760a",
          800: "#7a5e0d",
          900: "#664e10",
        },
        emerald: {
          DEFAULT: "#0F766E",
          light: "#0d9488",
          dark: "#0a5c55",
        },
        moroccan: {
          navy: "#0F172A",
          sand: "#F5F1E8",
          ivory: "#FAFAF9",
          terracotta: "#C25B33",
          cobalt: "#1255A0",
          rose: "#d4496a",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
        "3xl": "calc(var(--radius) + 16px)",
        "4xl": "2rem",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        shimmer: { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "slide-in-right": { from: { transform: "translateX(100%)" }, to: { transform: "translateX(0)" } },
        "slide-out-right": { from: { transform: "translateX(0)" }, to: { transform: "translateX(100%)" } },
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "scale-in": { from: { transform: "scale(0.95)", opacity: "0" }, to: { transform: "scale(1)", opacity: "1" } },
        float: { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-10px)" } },
        "moroccan-spin": { "0%": { transform: "rotate(0deg)" }, "100%": { transform: "rotate(360deg)" } },
        "pulse-gold": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(212, 175, 55, 0.4)" },
          "50%": { boxShadow: "0 0 0 8px rgba(212, 175, 55, 0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        shimmer: "shimmer 2s ease-in-out infinite",
        "slide-in-right": "slide-in-right 0.3s cubic-bezier(0.4,0,0.2,1)",
        "slide-out-right": "slide-out-right 0.25s cubic-bezier(0.4,0,0.2,1)",
        "fade-in": "fade-in 0.3s ease-out",
        "scale-in": "scale-in 0.25s ease-out",
        float: "float 5s ease-in-out infinite",
        spin: "moroccan-spin 0.7s linear infinite",
        "pulse-gold": "pulse-gold 2s ease-in-out infinite",
      },
      boxShadow: {
        luxury: "0 4px 24px -4px rgba(0,0,0,0.08), 0 1px 4px rgba(0,0,0,0.04)",
        "luxury-lg": "0 20px 60px -12px rgba(0,0,0,0.14), 0 4px 16px rgba(0,0,0,0.06)",
        brand: "0 0 28px rgba(15,118,110,0.35)",
        gold: "0 0 28px rgba(212,175,55,0.35)",
        card: "0 1px 3px rgba(0,0,0,0.06), 0 4px 16px rgba(0,0,0,0.04)",
        "inner-sm": "inset 0 1px 3px rgba(0,0,0,0.07)",
        "glass": "0 8px 32px rgba(15, 23, 42, 0.08), inset 0 1px 0 rgba(255,255,255,0.6)",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "moroccan-hero":
          "radial-gradient(ellipse at 0% 0%, rgba(15,118,110,0.3) 0%, transparent 50%), radial-gradient(ellipse at 100% 100%, rgba(212,175,55,0.2) 0%, transparent 50%), linear-gradient(135deg, #0F172A 0%, #0a2a26 50%, #0F172A 100%)",
        "gold-shimmer":
          "linear-gradient(90deg, transparent 0%, rgba(212,175,55,0.12) 40%, transparent 80%)",
        "emerald-glow":
          "radial-gradient(ellipse, rgba(15,118,110,0.25) 0%, transparent 70%)",
      },
      screens: { xs: "475px" },
    },
  },
  plugins: [tailwindcssAnimate],
};

export default config;
