import type { ThemeConfig } from "@/types/theme";
import { ThemeVersion } from "@/types/theme";

export const defaultThemes: Record<string, ThemeConfig> = {
  V1_CLASSIC: {
    version: ThemeVersion.V1_CLASSIC,
    name: "Classic",
    description: "Traditional e-commerce design with familiar patterns",
    colorPalette: {
      primary: "#2563eb",
      secondary: "#475569",
      accent: "#f59e0b",
      background: "#ffffff",
      foreground: "#0f172a",
      muted: "#f1f5f9",
      mutedForeground: "#64748b",
      border: "#e2e8f0",
      card: "#ffffff",
      cardForeground: "#0f172a",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      success: "#22c55e",
      warning: "#f59e0b",
      info: "#3b82f6",
    },
    typography: {
      fontFamily: {
        heading: "Inter, sans-serif",
        body: "Inter, sans-serif",
        mono: "JetBrains Mono, monospace",
      },
      fontSize: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
        "5xl": "3rem",
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: {
        tight: 1.25,
        normal: 1.5,
        relaxed: 1.75,
      },
    },
    spacing: {
      xs: "0.5rem",
      sm: "1rem",
      md: "1.5rem",
      lg: "2rem",
      xl: "3rem",
      "2xl": "4rem",
      "3xl": "6rem",
    },
    borderRadius: {
      none: "0",
      sm: "0.125rem",
      md: "0.375rem",
      lg: "0.5rem",
      xl: "0.75rem",
      "2xl": "1rem",
      full: "9999px",
    },
    shadows: {
      sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      md: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
      lg: "0 10px 15px -3px rgb(0 0 0 / 0.1)",
      xl: "0 20px 25px -5px rgb(0 0 0 / 0.1)",
      "2xl": "0 25px 50px -12px rgb(0 0 0 / 0.25)",
    },
    buttons: {
      primary: {
        background: "#2563eb",
        foreground: "#ffffff",
        hover: "#1d4ed8",
        borderRadius: "0.5rem",
        padding: "0.75rem 1.5rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
      secondary: {
        background: "#f1f5f9",
        foreground: "#0f172a",
        hover: "#e2e8f0",
        borderRadius: "0.5rem",
        padding: "0.75rem 1.5rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
      outline: {
        background: "transparent",
        foreground: "#0f172a",
        border: "#e2e8f0",
        hover: "#f1f5f9",
        borderRadius: "0.5rem",
        padding: "0.75rem 1.5rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
      ghost: {
        background: "transparent",
        foreground: "#0f172a",
        hover: "#f1f5f9",
        borderRadius: "0.5rem",
        padding: "0.75rem 1.5rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
    },
    header: {
      style: "sticky",
      backgroundColor: "#ffffff",
      textColor: "#0f172a",
      logoPosition: "left",
      showSearch: true,
      showCart: true,
      showWishlist: true,
      showUser: true,
      navigationStyle: "horizontal",
    },
    footer: {
      columns: 4,
      backgroundColor: "#0f172a",
      textColor: "#ffffff",
      showNewsletter: true,
      showSocialLinks: true,
      showPaymentIcons: true,
      showBadges: true,
    },
    layout: {
      containerWidth: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
      },
      contentPadding: "1.5rem",
      sectionSpacing: "4rem",
    },
    animations: {
      duration: {
        fast: 150,
        normal: 300,
        slow: 500,
      },
      easing: {
        ease: "ease",
        easeIn: "ease-in",
        easeOut: "ease-out",
        easeInOut: "ease-in-out",
      },
    },
    componentOverrides: {
      productCard: {
        showQuickAdd: true,
        showWishlist: true,
        showRating: true,
        showDiscount: true,
        imageAspectRatio: "3/3.5",
        hoverEffect: "zoom",
      },
      cartDrawer: {
        position: "right",
        showRelatedProducts: true,
        showCoupon: true,
      },
      checkout: {
        layout: "two-column",
        showOrderSummary: true,
      },
    },
    sectionStyles: {
      hero: {
        height: "600px",
        overlayOpacity: 0.4,
        textAlign: "left",
      },
      productGrid: {
        columns: 4,
        showFilters: true,
        showSort: true,
      },
    },
  },

  V2_MODERN: {
    version: ThemeVersion.V2_MODERN,
    name: "Modern",
    description: "Clean, minimalist design with bold typography",
    colorPalette: {
      primary: "#000000",
      secondary: "#6b7280",
      accent: "#8b5cf6",
      background: "#ffffff",
      foreground: "#000000",
      muted: "#f3f4f6",
      mutedForeground: "#6b7280",
      border: "#e5e7eb",
      card: "#ffffff",
      cardForeground: "#000000",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      success: "#10b981",
      warning: "#f59e0b",
      info: "#3b82f6",
    },
    typography: {
      fontFamily: {
        heading: "Space Grotesk, sans-serif",
        body: "Inter, sans-serif",
        mono: "JetBrains Mono, monospace",
      },
      fontSize: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "4xl": "2.5rem",
        "5xl": "3.5rem",
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: {
        tight: 1.2,
        normal: 1.6,
        relaxed: 1.8,
      },
    },
    spacing: {
      xs: "0.5rem",
      sm: "1rem",
      md: "1.5rem",
      lg: "2.5rem",
      xl: "4rem",
      "2xl": "6rem",
      "3xl": "8rem",
    },
    borderRadius: {
      none: "0",
      sm: "0.25rem",
      md: "0.5rem",
      lg: "0.75rem",
      xl: "1rem",
      "2xl": "1.5rem",
      full: "9999px",
    },
    shadows: {
      sm: "0 1px 3px 0 rgb(0 0 0 / 0.1)",
      md: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
      lg: "0 10px 15px -3px rgb(0 0 0 / 0.1)",
      xl: "0 20px 25px -5px rgb(0 0 0 / 0.1)",
      "2xl": "0 25px 50px -12px rgb(0 0 0 / 0.25)",
    },
    buttons: {
      primary: {
        background: "#000000",
        foreground: "#ffffff",
        hover: "#333333",
        borderRadius: "0.5rem",
        padding: "1rem 2rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
      secondary: {
        background: "#f3f4f6",
        foreground: "#000000",
        hover: "#e5e7eb",
        borderRadius: "0.5rem",
        padding: "1rem 2rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
      outline: {
        background: "transparent",
        foreground: "#000000",
        border: "#000000",
        hover: "#f3f4f6",
        borderRadius: "0.5rem",
        padding: "1rem 2rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
      ghost: {
        background: "transparent",
        foreground: "#000000",
        hover: "#f3f4f6",
        borderRadius: "0.5rem",
        padding: "1rem 2rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
    },
    header: {
      style: "sticky",
      backgroundColor: "#ffffff",
      textColor: "#000000",
      logoPosition: "left",
      showSearch: true,
      showCart: true,
      showWishlist: true,
      showUser: true,
      navigationStyle: "horizontal",
    },
    footer: {
      columns: 3,
      backgroundColor: "#000000",
      textColor: "#ffffff",
      showNewsletter: true,
      showSocialLinks: true,
      showPaymentIcons: true,
      showBadges: false,
    },
    layout: {
      containerWidth: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1400px",
      },
      contentPadding: "2rem",
      sectionSpacing: "6rem",
    },
    animations: {
      duration: {
        fast: 200,
        normal: 400,
        slow: 600,
      },
      easing: {
        ease: "cubic-bezier(0.4, 0, 0.2, 1)",
        easeIn: "cubic-bezier(0.4, 0, 1, 1)",
        easeOut: "cubic-bezier(0, 0, 0.2, 1)",
        easeInOut: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
    },
    componentOverrides: {
      productCard: {
        showQuickAdd: true,
        showWishlist: true,
        showRating: true,
        showDiscount: true,
        imageAspectRatio: "1/1",
        hoverEffect: "slide",
      },
      cartDrawer: {
        position: "right",
        showRelatedProducts: false,
        showCoupon: true,
      },
      checkout: {
        layout: "single",
        showOrderSummary: true,
      },
    },
    sectionStyles: {
      hero: {
        height: "700px",
        overlayOpacity: 0.2,
        textAlign: "center",
      },
      productGrid: {
        columns: 4,
        showFilters: true,
        showSort: true,
      },
    },
  },

  V3_PREMIUM: {
    version: ThemeVersion.V3_PREMIUM,
    name: "Premium",
    description: "Luxurious design with gold accents and elegant typography",
    colorPalette: {
      primary: "#d4af37",
      secondary: "#2c3e50",
      accent: "#c0392b",
      background: "#faf8f5",
      foreground: "#2c3e50",
      muted: "#f5f0eb",
      mutedForeground: "#7f8c8d",
      border: "#e8e0d5",
      card: "#ffffff",
      cardForeground: "#2c3e50",
      destructive: "#c0392b",
      destructiveForeground: "#ffffff",
      success: "#27ae60",
      warning: "#f39c12",
      info: "#2980b9",
    },
    typography: {
      fontFamily: {
        heading: "Playfair Display, serif",
        body: "Lato, sans-serif",
        mono: "JetBrains Mono, monospace",
      },
      fontSize: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "4xl": "2.5rem",
        "5xl": "3.5rem",
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: {
        tight: 1.2,
        normal: 1.6,
        relaxed: 1.8,
      },
    },
    spacing: {
      xs: "0.5rem",
      sm: "1rem",
      md: "1.5rem",
      lg: "2rem",
      xl: "3rem",
      "2xl": "5rem",
      "3xl": "7rem",
    },
    borderRadius: {
      none: "0",
      sm: "0.125rem",
      md: "0.25rem",
      lg: "0.375rem",
      xl: "0.5rem",
      "2xl": "0.75rem",
      full: "9999px",
    },
    shadows: {
      sm: "0 2px 4px 0 rgb(0 0 0 / 0.05)",
      md: "0 4px 8px -2px rgb(0 0 0 / 0.1)",
      lg: "0 12px 24px -4px rgb(0 0 0 / 0.15)",
      xl: "0 20px 40px -8px rgb(0 0 0 / 0.2)",
      "2xl": "0 30px 60px -12px rgb(0 0 0 / 0.25)",
    },
    buttons: {
      primary: {
        background: "#d4af37",
        foreground: "#ffffff",
        hover: "#b8962e",
        borderRadius: "0.25rem",
        padding: "0.875rem 2rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
      secondary: {
        background: "#2c3e50",
        foreground: "#ffffff",
        hover: "#1a252f",
        borderRadius: "0.25rem",
        padding: "0.875rem 2rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
      outline: {
        background: "transparent",
        foreground: "#2c3e50",
        border: "#d4af37",
        hover: "#faf8f5",
        borderRadius: "0.25rem",
        padding: "0.875rem 2rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
      ghost: {
        background: "transparent",
        foreground: "#2c3e50",
        hover: "#faf8f5",
        borderRadius: "0.25rem",
        padding: "0.875rem 2rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
    },
    header: {
      style: "sticky",
      backgroundColor: "#ffffff",
      textColor: "#2c3e50",
      logoPosition: "center",
      showSearch: true,
      showCart: true,
      showWishlist: true,
      showUser: true,
      navigationStyle: "horizontal",
    },
    footer: {
      columns: 5,
      backgroundColor: "#2c3e50",
      textColor: "#ffffff",
      showNewsletter: true,
      showSocialLinks: true,
      showPaymentIcons: true,
      showBadges: true,
    },
    layout: {
      containerWidth: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1200px",
      },
      contentPadding: "2rem",
      sectionSpacing: "5rem",
    },
    animations: {
      duration: {
        fast: 300,
        normal: 500,
        slow: 700,
      },
      easing: {
        ease: "ease",
        easeIn: "ease-in",
        easeOut: "ease-out",
        easeInOut: "ease-in-out",
      },
    },
    componentOverrides: {
      productCard: {
        showQuickAdd: true,
        showWishlist: true,
        showRating: true,
        showDiscount: true,
        imageAspectRatio: "3/4",
        hoverEffect: "fade",
      },
      cartDrawer: {
        position: "right",
        showRelatedProducts: true,
        showCoupon: true,
      },
      checkout: {
        layout: "two-column",
        showOrderSummary: true,
      },
    },
    sectionStyles: {
      hero: {
        height: "650px",
        overlayOpacity: 0.3,
        textAlign: "center",
      },
      productGrid: {
        columns: 4,
        showFilters: true,
        showSort: true,
      },
    },
  },

  V4_MINIMAL: {
    version: ThemeVersion.V4_MINIMAL,
    name: "Minimal",
    description: "Ultra-clean design with maximum whitespace",
    colorPalette: {
      primary: "#111111",
      secondary: "#666666",
      accent: "#111111",
      background: "#ffffff",
      foreground: "#111111",
      muted: "#f9f9f9",
      mutedForeground: "#999999",
      border: "#eeeeee",
      card: "#ffffff",
      cardForeground: "#111111",
      destructive: "#111111",
      destructiveForeground: "#ffffff",
      success: "#111111",
      warning: "#111111",
      info: "#111111",
    },
    typography: {
      fontFamily: {
        heading: "Inter, sans-serif",
        body: "Inter, sans-serif",
        mono: "JetBrains Mono, monospace",
      },
      fontSize: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
        "5xl": "3rem",
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: {
        tight: 1.2,
        normal: 1.5,
        relaxed: 1.7,
      },
    },
    spacing: {
      xs: "0.25rem",
      sm: "0.5rem",
      md: "1rem",
      lg: "1.5rem",
      xl: "2rem",
      "2xl": "3rem",
      "3xl": "4rem",
    },
    borderRadius: {
      none: "0",
      sm: "0",
      md: "0",
      lg: "0",
      xl: "0",
      "2xl": "0",
      full: "9999px",
    },
    shadows: {
      sm: "none",
      md: "none",
      lg: "none",
      xl: "none",
      "2xl": "none",
    },
    buttons: {
      primary: {
        background: "#111111",
        foreground: "#ffffff",
        hover: "#333333",
        borderRadius: "0",
        padding: "0.75rem 1.5rem",
        fontSize: "0.875rem",
        fontWeight: 500,
      },
      secondary: {
        background: "#f9f9f9",
        foreground: "#111111",
        hover: "#eeeeee",
        borderRadius: "0",
        padding: "0.75rem 1.5rem",
        fontSize: "0.875rem",
        fontWeight: 500,
      },
      outline: {
        background: "transparent",
        foreground: "#111111",
        border: "#111111",
        hover: "#f9f9f9",
        borderRadius: "0",
        padding: "0.75rem 1.5rem",
        fontSize: "0.875rem",
        fontWeight: 500,
      },
      ghost: {
        background: "transparent",
        foreground: "#111111",
        hover: "#f9f9f9",
        borderRadius: "0",
        padding: "0.75rem 1.5rem",
        fontSize: "0.875rem",
        fontWeight: 500,
      },
    },
    header: {
      style: "static",
      backgroundColor: "#ffffff",
      textColor: "#111111",
      logoPosition: "left",
      showSearch: true,
      showCart: true,
      showWishlist: false,
      showUser: true,
      navigationStyle: "horizontal",
    },
    footer: {
      columns: 2,
      backgroundColor: "#ffffff",
      textColor: "#111111",
      showNewsletter: false,
      showSocialLinks: false,
      showPaymentIcons: false,
      showBadges: false,
    },
    layout: {
      containerWidth: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1200px",
      },
      contentPadding: "1rem",
      sectionSpacing: "3rem",
    },
    animations: {
      duration: {
        fast: 100,
        normal: 200,
        slow: 300,
      },
      easing: {
        ease: "linear",
        easeIn: "linear",
        easeOut: "linear",
        easeInOut: "linear",
      },
    },
    componentOverrides: {
      productCard: {
        showQuickAdd: false,
        showWishlist: false,
        showRating: false,
        showDiscount: true,
        imageAspectRatio: "1/1",
        hoverEffect: "none",
      },
      cartDrawer: {
        position: "right",
        showRelatedProducts: false,
        showCoupon: false,
      },
      checkout: {
        layout: "single",
        showOrderSummary: true,
      },
    },
    sectionStyles: {
      hero: {
        height: "500px",
        overlayOpacity: 0,
        textAlign: "left",
      },
      productGrid: {
        columns: 3,
        showFilters: false,
        showSort: true,
      },
    },
  },

  V5_LUXURY: {
    version: ThemeVersion.V5_LUXURY,
    name: "Luxury",
    description: "Moroccan-inspired luxury with gold and navy accents",
    colorPalette: {
      primary: "#d4af37",
      secondary: "#1e3a5f",
      accent: "#c9a227",
      background: "#faf8f5",
      foreground: "#1e3a5f",
      muted: "#f5f0eb",
      mutedForeground: "#6b7280",
      border: "#e8e0d5",
      card: "#ffffff",
      cardForeground: "#1e3a5f",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      success: "#059669",
      warning: "#d97706",
      info: "#0284c7",
    },
    typography: {
      fontFamily: {
        heading: "Cormorant Garamond, serif",
        body: "Inter, sans-serif",
        mono: "JetBrains Mono, monospace",
      },
      fontSize: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "4xl": "2.75rem",
        "5xl": "4rem",
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: {
        tight: 1.15,
        normal: 1.6,
        relaxed: 1.85,
      },
    },
    spacing: {
      xs: "0.5rem",
      sm: "1rem",
      md: "1.5rem",
      lg: "2.5rem",
      xl: "4rem",
      "2xl": "6rem",
      "3xl": "8rem",
    },
    borderRadius: {
      none: "0",
      sm: "0.125rem",
      md: "0.375rem",
      lg: "0.5rem",
      xl: "0.75rem",
      "2xl": "1rem",
      full: "9999px",
    },
    shadows: {
      sm: "0 2px 4px 0 rgb(0 0 0 / 0.08)",
      md: "0 4px 8px -2px rgb(0 0 0 / 0.12)",
      lg: "0 12px 24px -4px rgb(0 0 0 / 0.15)",
      xl: "0 20px 40px -8px rgb(0 0 0 / 0.18)",
      "2xl": "0 30px 60px -12px rgb(0 0 0 / 0.22)",
    },
    buttons: {
      primary: {
        background: "linear-gradient(135deg, #d4af37 0%, #c9a227 100%)",
        foreground: "#ffffff",
        hover: "linear-gradient(135deg, #b8962e 0%, #a88a1f 100%)",
        borderRadius: "0.75rem",
        padding: "1rem 2.5rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
      secondary: {
        background: "#1e3a5f",
        foreground: "#ffffff",
        hover: "#152a45",
        borderRadius: "0.75rem",
        padding: "1rem 2.5rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
      outline: {
        background: "transparent",
        foreground: "#1e3a5f",
        border: "#d4af37",
        hover: "#faf8f5",
        borderRadius: "0.75rem",
        padding: "1rem 2.5rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
      ghost: {
        background: "transparent",
        foreground: "#1e3a5f",
        hover: "#faf8f5",
        borderRadius: "0.75rem",
        padding: "1rem 2.5rem",
        fontSize: "0.875rem",
        fontWeight: 600,
      },
    },
    header: {
      style: "sticky",
      backgroundColor: "#ffffff",
      textColor: "#1e3a5f",
      logoPosition: "center",
      showSearch: true,
      showCart: true,
      showWishlist: true,
      showUser: true,
      navigationStyle: "mega",
    },
    footer: {
      columns: 5,
      backgroundColor: "#1e3a5f",
      textColor: "#ffffff",
      showNewsletter: true,
      showSocialLinks: true,
      showPaymentIcons: true,
      showBadges: true,
    },
    layout: {
      containerWidth: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
      },
      contentPadding: "2rem",
      sectionSpacing: "6rem",
    },
    animations: {
      duration: {
        fast: 300,
        normal: 500,
        slow: 700,
      },
      easing: {
        ease: "cubic-bezier(0.4, 0, 0.2, 1)",
        easeIn: "cubic-bezier(0.4, 0, 1, 1)",
        easeOut: "cubic-bezier(0, 0, 0.2, 1)",
        easeInOut: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
    },
    componentOverrides: {
      productCard: {
        showQuickAdd: true,
        showWishlist: true,
        showRating: true,
        showDiscount: true,
        imageAspectRatio: "3/3.5",
        hoverEffect: "zoom",
      },
      cartDrawer: {
        position: "right",
        showRelatedProducts: true,
        showCoupon: true,
      },
      checkout: {
        layout: "two-column",
        showOrderSummary: true,
      },
    },
    sectionStyles: {
      hero: {
        height: "700px",
        overlayOpacity: 0.35,
        textAlign: "center",
      },
      productGrid: {
        columns: 4,
        showFilters: true,
        showSort: true,
      },
    },
  },

  V5_LUXURY_MOROCCO: {
    version: ThemeVersion.V4_MINIMAL,
    name: "Luxury Morocco",
    description: "Minimal Luxury — Moroccan identity with emerald & gold accents",
    colorPalette: {
      primary: "#0D7A5E",
      secondary: "#0b3f36",
      accent: "#C89B3C",
      background: "#ffffff",
      foreground: "#0b0b0b",
      muted: "#f5f5f5",
      mutedForeground: "#6b6b6b",
      border: "#eeeeee",
      card: "#ffffff",
      cardForeground: "#0b0b0b",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      success: "#10b981",
      warning: "#f59e0b",
      info: "#3b82f6",
    },
    typography: {
      fontFamily: {
        heading: "Playfair Display, serif",
        body: "Inter, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial",
        mono: "JetBrains Mono, monospace",
      },
      fontSize: {
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        xl: "1.5rem",
        "2xl": "2rem",
        "3xl": "2.75rem",
        "4xl": "3.75rem",
        "5xl": "5rem",
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: {
        tight: 1.08,
        normal: 1.5,
        relaxed: 1.85,
      },
    },
    spacing: {
      xs: "0.25rem",
      sm: "0.5rem",
      md: "1rem",
      lg: "2rem",
      xl: "3rem",
      "2xl": "5rem",
      "3xl": "8rem",
    },
    borderRadius: {
      none: "0",
      sm: "0.25rem",
      md: "0.5rem",
      lg: "0.75rem",
      xl: "1rem",
      "2xl": "1.5rem",
      full: "9999px",
    },
    shadows: {
      sm: "0 6px 18px rgba(13, 122, 94, 0.06)",
      md: "0 14px 40px rgba(13, 122, 94, 0.08)",
      lg: "0 30px 80px rgba(2, 10, 18, 0.2)",
      xl: "0 50px 120px rgba(2, 6, 10, 0.28)",
      "2xl": "0 80px 200px rgba(2, 6, 10, 0.32)",
    },
    buttons: {
      primary: {
        background: "#0D7A5E",
        foreground: "#ffffff",
        hover: "#0b6b51",
        borderRadius: "0.75rem",
        padding: "1rem 2rem",
        fontSize: "1rem",
        fontWeight: 600,
      },
      secondary: {
        background: "#ffffff",
        foreground: "#0D7A5E",
        hover: "#f7f7f7",
        borderRadius: "0.75rem",
        padding: "0.875rem 1.75rem",
        fontSize: "0.95rem",
        fontWeight: 600,
      },
      outline: {
        background: "transparent",
        foreground: "#0D7A5E",
        border: "#0D7A5E",
        hover: "#f7f7f7",
        borderRadius: "0.75rem",
        padding: "0.875rem 1.75rem",
        fontSize: "0.95rem",
        fontWeight: 600,
      },
      ghost: {
        background: "transparent",
        foreground: "#0b0b0b",
        hover: "#fafafa",
        borderRadius: "0.75rem",
        padding: "0.75rem 1.5rem",
        fontSize: "0.95rem",
        fontWeight: 500,
      },
    },
    header: {
      style: "sticky",
      backgroundColor: "rgba(255,255,255,0.9)",
      textColor: "#0b0b0b",
      logoPosition: "left",
      showSearch: true,
      showCart: true,
      showWishlist: true,
      showUser: true,
      navigationStyle: "horizontal",
    },
    footer: {
      columns: 5,
      backgroundColor: "#070707",
      textColor: "#f7f5f2",
      showNewsletter: true,
      showSocialLinks: true,
      showPaymentIcons: true,
      showBadges: true,
    },
    layout: {
      containerWidth: {
        sm: "640px",
        md: "768px",
        lg: "1120px",
        xl: "1400px",
      },
      contentPadding: "2rem",
      sectionSpacing: "4.5rem",
    },
    animations: {
      duration: {
        fast: 120,
        normal: 260,
        slow: 480,
      },
      easing: {
        ease: "cubic-bezier(0.2, 0.8, 0.2, 1)",
        easeIn: "cubic-bezier(0.2, 0.9, 0.2, 1)",
        easeOut: "cubic-bezier(0.1, 0.7, 0.1, 1)",
        easeInOut: "cubic-bezier(0.2, 0.8, 0.2, 1)",
      },
    },
    componentOverrides: {
      productCard: {
        showQuickAdd: true,
        showWishlist: true,
        showRating: true,
        showDiscount: true,
        imageAspectRatio: "4/5",
        hoverEffect: "zoom",
      },
      cartDrawer: {
        position: "right",
        showRelatedProducts: true,
        showCoupon: true,
      },
      checkout: {
        layout: "two-column",
        showOrderSummary: true,
      },
    },
    sectionStyles: {
      hero: {
        height: "720px",
        overlayOpacity: 0.3,
        textAlign: "center",
      },
      productGrid: {
        columns: 4,
        showFilters: true,
        showSort: true,
      },
    },
  },
};
