"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, Button, Badge, Textarea, Label, Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui";
import { 
  CheckCircle, 
  XCircle, 
  Clock, 
  Send,
  Eye,
  Edit,
  History,
  AlertTriangle,
  FileText,
  Calendar,
  User
} from "lucide-react";

type WorkflowStatus = "DRAFT" | "READY" | "REVIEW_REQUIRED" | "PUBLISHED" | "FAILED" | "ARCHIVED";
type WorkflowAction = "approve" | "reject" | "request_changes" | "publish" | "archive" | "duplicate";

interface ReviewWorkflowProps {
  currentStatus: WorkflowStatus;
  onStatusChange: (status: WorkflowStatus, note?: string) => void;
  disabled?: boolean;
  showHistory?: boolean;
}

interface WorkflowStep {
  id: string;
  status: WorkflowStatus;
  actor: string;
  timestamp: Date;
  note?: string;
}

const WORKFLOW_STEPS: Array<{
  status: WorkflowStatus;
  label: string;
  icon: any;
  color: string;
}> = [
  {
    status: "DRAFT",
    label: "Draft",
    icon: FileText,
    color: "text-gray-600 bg-gray-50",
  },
  {
    status: "READY",
    label: "Ready",
    icon: CheckCircle,
    color: "text-blue-600 bg-blue-50",
  },
  {
    status: "REVIEW_REQUIRED",
    label: "Needs Review",
    icon: AlertTriangle,
    color: "text-amber-600 bg-amber-50",
  },
  {
    status: "PUBLISHED",
    label: "Published",
    icon: CheckCircle,
    color: "text-green-600 bg-green-50",
  },
  {
    status: "FAILED",
    label: "Failed",
    icon: XCircle,
    color: "text-red-600 bg-red-50",
  },
  {
    status: "ARCHIVED",
    label: "Archived",
    icon: History,
    color: "text-purple-600 bg-purple-50",
  },
];

const STATUS_TRANSITIONS: Record<WorkflowStatus, WorkflowStatus[]> = {
  DRAFT: ["READY", "FAILED", "ARCHIVED"],
  READY: ["REVIEW_REQUIRED", "PUBLISHED", "DRAFT", "ARCHIVED"],
  REVIEW_REQUIRED: ["READY", "PUBLISHED", "DRAFT", "FAILED", "ARCHIVED"],
  PUBLISHED: ["ARCHIVED"],
  FAILED: ["DRAFT", "ARCHIVED"],
  ARCHIVED: ["DRAFT"],
};

export function ReviewWorkflow({ 
  currentStatus, 
  onStatusChange, 
  disabled = false,
  showHistory = true 
}: ReviewWorkflowProps) {
  const [selectedAction, setSelectedAction] = useState<WorkflowAction | null>(null);
  const [reviewNote, setReviewNote] = useState("");
  const [showNoteInput, setShowNoteInput] = useState(false);
  const [history] = useState<WorkflowStep[]>([
    {
      id: "1",
      status: "DRAFT",
      actor: "AI System",
      timestamp: new Date(Date.now() - 3600000),
      note: "Auto-generated by AI Product Studio",
    },
  ]);

  const currentStep = WORKFLOW_STEPS.find(step => step.status === currentStatus);
  const availableTransitions = STATUS_TRANSITIONS[currentStatus] || [];

  const handleAction = (action: WorkflowAction) => {
    setSelectedAction(action);
    if (action === "reject" || action === "request_changes") {
      setShowNoteInput(true);
    } else {
      executeAction(action);
    }
  };

  const executeAction = (action: WorkflowAction, note?: string) => {
    let newStatus: WorkflowStatus;
    
    switch (action) {
      case "approve":
        newStatus = "READY";
        break;
      case "reject":
        newStatus = "FAILED";
        break;
      case "request_changes":
        newStatus = "DRAFT";
        break;
      case "publish":
        newStatus = "PUBLISHED";
        break;
      case "archive":
        newStatus = "ARCHIVED";
        break;
      case "duplicate":
        newStatus = "DRAFT";
        break;
      default:
        return;
    }
    
    onStatusChange(newStatus, note);
    setSelectedAction(null);
    setShowNoteInput(false);
    setReviewNote("");
  };

  const getStatusColor = (status: WorkflowStatus) => {
    const step = WORKFLOW_STEPS.find(s => s.status === status);
    return step?.color || "text-gray-600 bg-gray-50";
  };

  const canTransitionTo = (status: WorkflowStatus) => {
    return availableTransitions.includes(status);
  };

  return (
    <div className="space-y-6">
      {/* Current Status Card */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            {currentStep && <currentStep.icon className="h-5 w-5" />}
            Review Workflow
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Current Status */}
          <div className={`flex items-center justify-between p-6 rounded-lg border-2 ${getStatusColor(currentStatus)}`}>
            <div className="flex items-center gap-4">
              {currentStep && (
                <div className={`p-4 rounded-full ${currentStep.color}`}>
                  <currentStep.icon className="h-8 w-8" />
                </div>
              )}
              <div>
                <h3 className="text-2xl font-bold">{currentStep?.label}</h3>
                <p className="text-sm opacity-75">Current workflow status</p>
              </div>
            </div>
            <Badge variant="outline" className="text-lg px-4 py-2">
              {currentStatus}
            </Badge>
          </div>

          {/* Workflow Progress */}
          <div className="flex items-center justify-between">
            {WORKFLOW_STEPS.slice(0, 5).map((step, index) => {
              const Icon = step.icon;
              const isActive = step.status === currentStatus;
              const isPast = WORKFLOW_STEPS.findIndex(s => s.status === currentStatus) > index;
              
              return (
                <div key={step.status} className="flex-1 flex items-center">
                  <div className="flex flex-col items-center">
                    <div className={`p-3 rounded-full border-2 transition-all ${
                      isActive 
                        ? "border-brand-600 bg-brand-50 text-brand-600 scale-110" 
                        : isPast
                        ? "border-green-600 bg-green-50 text-green-600"
                        : "border-gray-300 bg-gray-50 text-gray-400"
                    }`}>
                      <Icon className="h-5 w-5" />
                    </div>
                    <span className={`text-xs mt-2 font-medium ${
                      isActive ? "text-brand-600" : isPast ? "text-green-600" : "text-gray-400"
                    }`}>
                      {step.label}
                    </span>
                  </div>
                  {index < WORKFLOW_STEPS.slice(0, 5).length - 1 && (
                    <div className={`flex-1 h-1 mx-2 rounded ${
                      isPast ? "bg-green-600" : "bg-gray-200"
                    }`} />
                  )}
                </div>
              );
            })}
          </div>

          {/* Available Actions */}
          <div>
            <Label className="mb-3 block">Available Actions</Label>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
              {currentStatus === "DRAFT" && (
                <>
                  <Button
                    variant="outline"
                    className="h-auto py-4 flex flex-col items-center gap-2"
                    onClick={() => !disabled && handleAction("approve")}
                    disabled={disabled}
                  >
                    <CheckCircle className="h-5 w-5 text-green-600" />
                    <span>Mark Ready</span>
                  </Button>
                  <Button
                    variant="outline"
                    className="h-auto py-4 flex flex-col items-center gap-2"
                    onClick={() => !disabled && handleAction("archive")}
                    disabled={disabled}
                  >
                    <History className="h-5 w-5 text-purple-600" />
                    <span>Archive</span>
                  </Button>
                </>
              )}
              
              {currentStatus === "READY" && (
                <>
                  <Button
                    variant="outline"
                    className="h-auto py-4 flex flex-col items-center gap-2"
                    onClick={() => !disabled && handleAction("publish")}
                    disabled={disabled}
                  >
                    <Send className="h-5 w-5 text-green-600" />
                    <span>Publish</span>
                  </Button>
                  <Button
                    variant="outline"
                    className="h-auto py-4 flex flex-col items-center gap-2"
                    onClick={() => !disabled && handleAction("request_changes")}
                    disabled={disabled}
                  >
                    <Edit className="h-5 w-5 text-amber-600" />
                    <span>Request Changes</span>
                  </Button>
                </>
              )}
              
              {currentStatus === "REVIEW_REQUIRED" && (
                <>
                  <Button
                    variant="outline"
                    className="h-auto py-4 flex flex-col items-center gap-2"
                    onClick={() => !disabled && handleAction("approve")}
                    disabled={disabled}
                  >
                    <CheckCircle className="h-5 w-5 text-green-600" />
                    <span>Approve</span>
                  </Button>
                  <Button
                    variant="outline"
                    className="h-auto py-4 flex flex-col items-center gap-2"
                    onClick={() => !disabled && handleAction("reject")}
                    disabled={disabled}
                  >
                    <XCircle className="h-5 w-5 text-red-600" />
                    <span>Reject</span>
                  </Button>
                  <Button
                    variant="outline"
                    className="h-auto py-4 flex flex-col items-center gap-2"
                    onClick={() => !disabled && handleAction("request_changes")}
                    disabled={disabled}
                  >
                    <Edit className="h-5 w-5 text-amber-600" />
                    <span>Request Changes</span>
                  </Button>
                </>
              )}
              
              {currentStatus === "PUBLISHED" && (
                <Button
                  variant="outline"
                  className="h-auto py-4 flex flex-col items-center gap-2"
                  onClick={() => !disabled && handleAction("archive")}
                  disabled={disabled}
                >
                  <History className="h-5 w-5 text-purple-600" />
                  <span>Archive</span>
                </Button>
              )}
              
              {currentStatus === "FAILED" && (
                <>
                  <Button
                    variant="outline"
                    className="h-auto py-4 flex flex-col items-center gap-2"
                    onClick={() => !disabled && handleAction("duplicate")}
                    disabled={disabled}
                  >
                    <FileText className="h-5 w-5 text-blue-600" />
                    <span>Duplicate & Retry</span>
                  </Button>
                  <Button
                    variant="outline"
                    className="h-auto py-4 flex flex-col items-center gap-2"
                    onClick={() => !disabled && handleAction("archive")}
                    disabled={disabled}
                  >
                    <History className="h-5 w-5 text-purple-600" />
                    <span>Archive</span>
                  </Button>
                </>
              )}
            </div>
          </div>

          {/* Review Note Input */}
          {showNoteInput && (
            <div className="space-y-3 p-4 bg-muted rounded-lg border">
              <Label>Review Note (Required)</Label>
              <Textarea
                value={reviewNote}
                onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setReviewNote(e.target.value)}
                placeholder="Add your review notes here..."
                className="min-h-[100px]"
              />
              <div className="flex gap-2">
                <Button
                  onClick={() => executeAction(selectedAction!, reviewNote)}
                  disabled={!reviewNote.trim() || disabled}
                >
                  Submit Review
                </Button>
                <Button
                  variant="outline"
                  onClick={() => {
                    setShowNoteInput(false);
                    setSelectedAction(null);
                    setReviewNote("");
                  }}
                >
                  Cancel
                </Button>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Workflow History */}
      {showHistory && history.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <History className="h-5 w-5" />
              Workflow History
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {history.map((step, index) => {
                const stepConfig = WORKFLOW_STEPS.find(s => s.status === step.status);
                const Icon = stepConfig?.icon || Clock;
                
                return (
                  <div key={step.id} className="flex items-start gap-4">
                    <div className={`p-2 rounded-full ${stepConfig?.color}`}>
                      <Icon className="h-4 w-4" />
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <span className="font-medium">{stepConfig?.label}</span>
                          <Badge variant="outline" className="text-xs">
                            {step.status}
                          </Badge>
                        </div>
                        <div className="flex items-center gap-2 text-sm text-muted-foreground">
                          <User className="h-3 w-3" />
                          <span>{step.actor}</span>
                          <Calendar className="h-3 w-3 ml-2" />
                          <span>{step.timestamp.toLocaleString()}</span>
                        </div>
                      </div>
                      {step.note && (
                        <p className="text-sm text-muted-foreground mt-1">{step.note}</p>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
